### ISSUE TITLE
Unit testing, correctness

### ISSUE THREAD

**Issue by r-barnes** [OmnesRes/GRIMMER#1]
The presence of large numbers of globals in the source makes it harder to trust ([link](http://wiki.c2.com/?GlobalVariablesAreBad), [link](https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil)).

The lack of [unit](https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it) [tests](https://www.geeksforgeeks.org/unit-testing-python-unittest/) is also problematic.

This software is meant to improve and enforce best practices in research statistics, but exhibits poor adherence to best practices in programming :-(

**Comment by OmnesRes** [comment]
This brute force method is actually not needed to check variances.  Following publication some people came up with a formula (appendix of https://psyarxiv.com/7shr8/).
